#!/bin/bash

COMMAND_DIR="/usr/share/ddcommands"

if [ -z "$1" ]; then
    echo "Uso: ddcommands [comando]"
    exit 1
fi

FILE="$COMMAND_DIR/$1.md"

if [ -f "$FILE" ]; then

    # Verificar si glow está instalado
    if command -v glow >/dev/null 2>&1; then
        glow -p "$FILE"
    else
        cat "$FILE"
    fi

else
    echo "El comando '$1' no está disponible en ddcommands."
fi 